#!/bin/bash

declare -i args
args=$#           # Number of args passed.
lastarg=${!args}
lastarg1=${!#}
lastarg2=${$args}
echo "number of all args : $args"
echo "first arg is : ${1}"
echo "last arg is : $lastarg"
echo "last arg is  (version2): $lastarg1"
echo "last arg is  (version3): $lastarg2"
# Note: This is an *indirect reference* to $args ...


# Or:       lastarg=${!#}             (Thanks, Chris Monson.)
# This is an *indirect reference* to the $# variable.
# Note that lastarg=${!$#} doesn't work.
